/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c032b0d1-28ba-47d6-b1df-44c5982f59a7",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_HqmXV9JQ6",
    "aws_user_pools_web_client_id": "5rtjagr5oqoqvm0ucibkm070nf",
    "oauth": {},
    "aws_mobile_analytics_app_id": "32071b03d56f49b5a8187791b97c2632",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://oeccstmyajdg3cnz7he6gdzgqa.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
